### PR TITLE
Js productviews

### LINKED ISSUE #8: User can view all product categories
**Given** a user is viewing any page on the Bangazon site
**When** the user performs a gesture on the *Product Categories* hyperlink
**Then** the user will see a view containing a list of all product categories 
**And** next to the category name, the number of products in that category will be displayed
**And** the first three products in the category will be displayed beneath each category, that are hyperlinks to products descriptions. 

##### Sample

```
Electronics (15)
    Dryer
    HD Television
    Sony Walkman

Sporting Goods (7)
    Football
    Ice skates
    Basketball hoop
```

### PR DESCRIPTION
**Pull request by jessnswift**
## Link to Ticket

Autolink format: hashtag and number, ex: #1094

Closes #8 

```sh
git fetch --all
git checkout js_productviews
code .
django_data.sh website faker_factory
go to   http://127.0.0.1:8000/website/product_types
```

## Description of Proposed Changes
Listing products categories and quantity

## Steps to Test
1. Make sure there is 1 product category displayed on the page per product type in the database.
1. There should be a total displayed beside the product type name.
1. Below the product category name, there will be 3 products displays (if enough products were generated per line 5 on steps above.
1. The product should be clickable but lead to a error page until it is implemented. 

Outline the steps to test

## Impacted Areas in Application

**New Files**:

**Modified Files**:

**Deleted Files**:

## Mentions @username

Tag users that need to review this code

## Testing

* [ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
* [ ] I certify that all existing tests pass
* [ ] The README has been updated with complete information
* [ ] All classes and functions have docstrings
* [ ] All file names match class and describe use (ex: Employee_Model.py, Employee_View.py)

## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Definition of Done

1. The project must be fully documented. This includes the following:
   1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
   1. Every class must be documented with purpose, author, and methods.
   1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
1. Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each

### CODE REVIEW

**Comment by MrErin** [comment]
Make the faker_factory change on your branch and push it up (one more commit for you!)

**Comment by MrErin** [comment]
👍

**Comment by obscure-shadow** [comment]
some stuff like... showed up on the page or whatever... 👍

**Comment by JacobAndrewSmith92** [comment]
💯

**Pull request merged**
