### PR TITLE
Cr migration of models

### LINKED ISSUE #24: Developers need models
Build out the models according to the ERD

### PR DESCRIPTION
**Pull request by CashewRose**
## Link to Ticket

Closes #24 

## Steps to Test

```sh
git fetch --all
git checkout cr_migrationOfModels
python manage.py makemigrations
python manage.py migrate
python manage.py runserver
```

1. Open db browsers and double check all models have made it in there correctly
1. In server register yourself as a user
1. Should see username and welcome page
1. Logout
1. Login with incorrect information
1. You should be shown an incorrect credentials display
1. Login with the information you used to register
1. Should sign you back in and display your username
1. Confirm your user information is in the db

## Mentions @username

@jessnswift @obscure-shadow @MrErin @JacobAndrewSmith92 

## Testing

* [ ] All file names match class and describe use (ex: Employee_Model.py, Employee_View.py)

### CODE REVIEW

**Comment by JacobAndrewSmith92** [comment]
💯

**Comment by MrErin** [comment]
👍

**Comment by CashewRose** [comment]
@MrErin I feel personally attacked by team leader. Anyone want to form a union? Asking for a friend

**Comment by JacobAndrewSmith92** [comment]
💯

**Comment by MrErin** [comment]
🔨 to your union.
👍  to your PR.

**Pull request merged**
