### PR TITLE
Dp product category

### PR DESCRIPTION
**Pull request by obscure-shadow**
## Link to Ticket

Closes #
#9 

## Description of Proposed Changes
turned all mention of categories for products into links that go to a page that list every product in that particular category
## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout dp_product_category
```
1. make sure all your ish is runnin' or w/e.
1. go to the webpage an click on "all product" n check that the product category is like... a link... 
1. click on a produckt or whuteva, n see if the category link goes back to the list of everything in that category
1. gimme a hell yeah 👍 

## Impacted Areas in Application

**New Files**:
yes

**Modified Files**:
also yes

**Deleted Files**:

i don't think so...

## Mentions @username

Tag users that need to review this code

## Testing

* [ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
* [ ] I certify that all existing tests pass
* [ ] The README has been updated with complete information
* [ ] All classes and functions have docstrings
* [ ] All file names match class and describe use (ex: Employee_Model.py, Employee_View.py)

## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Definition of Done

1. The project must be fully documented. This includes the following:
   1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
   1. Every class must be documented with purpose, author, and methods.
   1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
1. Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each

### CODE REVIEW

**Comment by MrErin** [comment]
You're weird. 💥

**Comment by CashewRose** [comment]
What if I am progooset?

**Comment by obscure-shadow** [comment]
as long as u can click it it's whatever ;)

**Comment by JacobAndrewSmith92** [comment]
hell yeah 💯

**Pull request merged**
