### PR TITLE
Listing payment type name instead of payment type id

### PR DESCRIPTION
**Pull request by jacobxcodes**
## Link to Ticket

Autolink format: hashtag and number, ex: #1094

Closes #

## Description of Proposed Changes
ONLY CHANGE: Displaying Payment Type name instead of its ID in the payment detail page.

## Steps to Test
1. Run virtual machine
1. Run migrations
1. Create some users
1. Create a payment type
1. Make sure when a payment type is made that the name generates the payment type in the detail page.
1. Be awesome

Outline the steps to test

```
git fetch --all
git checkout js_refactor_payment
```

## Impacted Areas in Application

**New Files**:

**Modified Files**:
```
	modified:   website/templates/account/payment_option_detail.html
	modified:   website/templates/account/payment_option_list.html
	modified:   website/views/payment_option_view.py
```
**Deleted Files**:

## Mentions @username

Tag users that need to review this code

## Testing

* [ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
* [ ] I certify that all existing tests pass
* [ ] The README has been updated with complete information
* [ ] All classes and functions have docstrings
* [ ] All file names match class and describe use (ex: Employee_Model.py, Employee_View.py)

## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Definition of Done

1. The project must be fully documented. This includes the following:
   1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
   1. Every class must be documented with purpose, author, and methods.
   1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
1. Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each

### CODE REVIEW

**Comment by CashewRose** [comment]
Be awesome <3

**Comment by obscure-shadow** [comment]
i'm being so awesome right now

**Comment by obscure-shadow** [comment]
:shipit:

**Comment by obscure-shadow** [comment]
hell yeah

**Comment by MrErin** [comment]
do it 💥

**Pull request merged**
