### PR TITLE
Em product detail view

### LINKED ISSUE #35: User needs to be able to view product details
## Story

As a user, when I click on a hyperlinked product title, I expect to be directed to a page listing the details of the product.

## Acceptance Criteria

**Given:** A user is viewing bangazon's awesome page
**When:** The user clicks on a hyperlinked product
**Then:** A page should display listing the product details and seller's information

### PR DESCRIPTION
**Pull request by MrErin**
## Link to Ticket

Closes #35 

## Description of Proposed Changes

* Adds a product detail page available whenever the user clicks on a product.
* Changes product model to require all prices are positive numbers

## Steps to Test

```sh
git fetch --all
git checkout em_product_detail_view
```

1. start virtualenv, run server, run faker data if necessary
1. Navigate to the bangazon home page. Click on "All Products", then select any product from the list
1. Open DB browser and verify that the product detail page displays the correct information on the product, the product's category, and the seller.

## Impacted Areas in Application

**New**
* website/templates/product/detail.html
* website/views/product_detail_view.py

**Modified**
* bangazonweb/urls.py
* website/models/Product_Model.py
* website/templates/index.html
* website/templates/login.html
* website/templates/register.html
* website/urls.py
* website/views/__init__.py

## Mentions @username

@JacobAndrewSmith92 @jessnswift @CashewRose @obscure-shadow 

## Testing

* [ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
* [ ] I certify that all existing tests pass
* [ ] The README has been updated with complete information
* [ ] All classes and functions have docstrings
* [ ] All file names match class and describe use (ex: Employee_Model.py, Employee_View.py)

### CODE REVIEW

**Comment by obscure-shadow** [comment]
looks good :shipit:

**Comment by JacobAndrewSmith92** [comment]
Looks good! 💯

**Comment by JacobAndrewSmith92** [comment]
Will add a sticky navbar so that when scrolling down the page the user still has controls to navigate on the site.

**Comment by JacobAndrewSmith92** [comment]
:shipit:

**Pull request merged**
