### PR TITLE
Faker SQL Scripts

### LINKED ISSUE #23: SQL Script - Categories, Update upon further discussion
## Story
When the user visits our page, certain faker data should make sense. 

## Acceptance Criteria

**Given:**  A user wants to see a list of categories, payment types, or customers
**When:** the user clicks the dropdown for either a payment type or category name
**Then:** they should be able to select a coherent category name or payment type 
**And:** the users name and information should be relevant

### PR DESCRIPTION
**Pull request by JacobAndrewSmith92**
## Link to Ticket

Autolink format: hashtag and number, ex: #1094

Closes #23 

## Description of Proposed Changes
New directory: sql
New file: bangazon.sql

## Steps to Test
1. checkout branch
1. run virtual machine
1. see that sql directory has a file named bangazon.sql
1. make all necessary migrations 
1. Open DB Browser with db.sqlite3
1. Navigate to 'Execute SQL'
1. Run Script
1. Browse website_customer, website_product_type, & website_payment_type make sure it inserted successful
1. Use :shipit: if completed
1. AND ONLY  :shipit: 

```
git fetch --all
git checkout js_sql_scripts
```

## Impacted Areas in Application

**New Files**:
sql/bangazon.sql

**Modified Files**:

**Deleted Files**:

## Mentions @username

Tag users that need to review this code

## Testing

* [ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
* [ ] I certify that all existing tests pass
* [ ] The README has been updated with complete information
* [ ] All classes and functions have docstrings
* [ ] All file names match class and describe use (ex: Employee_Model.py, Employee_View.py)

## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Definition of Done

1. The project must be fully documented. This includes the following:
   1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
   1. Every class must be documented with purpose, author, and methods.
   1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
1. Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each

### CODE REVIEW

**Comment by MrErin** [comment]
FIX YO SPELLING

**Comment by MrErin** [comment]
👍

**Comment by CashewRose** [comment]
🚢  to quote @MrErin's tyranny 🔨 :shipit: !!!

**Comment by MrErin** [comment]
I'm not changing mine. Suck it, squirrel.

**Pull request merged**
